# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171017_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='abc@example.com', max_length=75, unique=True),
        ),
    ]
